matrix:
  RUST: [stable, beta, nightly]

steps:
  - name: lean
    # We have to use an image that has both rustup and lean
    image: rust
    commands:
      - curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y
      - rustup default $RUST
      - lake update
      - lake build
      - lake test
    when:
      event: [push, pull_request]
  - name: rust
    image: rust
    commands:
      - rustup default $RUST
      - cargo check
      - cargo test
    when:
      event: [push, pull_request]
