matrix:
  platform:
   - darwin/aarch64
   - linux/amd64

steps:
  - name: test
    # We have to use an image that has both rustup and lean, because the lean
    # part depends on rust and the rust part depends on lean.
    image: ubuntu
    commands:
      - curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y
      - . ~/.profile
      - apt-get update && apt-get install -y libasound2-dev alda

      - lake exe cache get
      - lake build
      - lake test
    when:
      event: [push, pull_request]
      platform: [darwin/aarch64, linux/amd64]
